### PR TITLE
Reorganize request_api app

### PR DESCRIPTION
**Pull request by harish-sethuraman**

### CODE REVIEW

**Comment by Saif-Shines** [comment]
There are two files those can be removed
1. zip file that is generated, the zip folder
2. iparam_test_data is no longer required

Can you please remove them?

**Comment by harish-sethuraman** [comment]
@Saif-Shines The iparam_test_data.json is removed

**Comment by Saif-Shines** [comment]
Right!

**Comment by harish-sethuraman** [comment]
@Saif-Shines shall i remove the dist folder ? along with the zip in it or the zip alone ?

**Comment by Saif-Shines** [comment]
Complete /dist/ folder would be redundant, @harish-sethuraman !

**Comment by harish-sethuraman** [comment]
@Saif-Shines Removed it thanks 😃

**Review by ravirajsubramanian — APPROVED** [review]

**Pull request merged**
