### PR TITLE
fix: refactor tickets_close_interceptor app

### PR DESCRIPTION
**Pull request by RShalman**

### CODE REVIEW

**Review by Saif-Shines — APPROVED** [review]

**Comment by Saif-Shines** [comment]
Silently yet, accurately done! @RShalman Thank you so much for your contribution!

**Comment by RShalman** [comment]
Don't quite get what's the reason of this error.

**Comment by RShalman** [comment]
> Silently yet, accurately done! @RShalman Thank you so much for your contribution!

Was happy to contribute, mate!)

**Comment by Saif-Shines** [comment]
> Don't quite get what's the reason of this error.

Do you mean the checks failing?

**Comment by RShalman** [comment]
> > Don't quite get what's the reason of this error.
> 
> Do you mean the checks failing?

Yep)
And plz, asd the "hacktoberfest" topic to your repository if you wish to participate.

PR count otherwise doesn't change(

**Comment by Saif-Shines** [comment]
The `Hacktoberfest` label is added to this PR and also to the Issue referenced. I hope that should have your effort counted for Hacktoberfest as well. 

If not please let us know, we will try to correct if something that we(as maintainers) are doing is wrong.

**Comment by RShalman** [comment]
> The `Hacktoberfest` label is added to this PR and also to the Issue referenced. I hope that should have your effort counted for Hacktoberfest as well.
> 
> If not please let us know, we will try to correct if something that we(as maintainers) are doing is wrong.

I guess they mean you add not only to PR but to repo desc or smth. like that.

**Comment by Saif-Shines** [comment]
> I guess they mean you add not only to PR but to repo desc or smth. like that.

You are correct. Seems like Digital Ocean has [made updates to the rules of Hacktoberfest.](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

I am following up with our teams on this. If you don't see your count updated within a week. Do let us know.

**Comment by RShalman** [comment]
> > I guess they mean you add not only to PR but to repo desc or smth. like that.
> 
> You are correct. Seems like Digital Ocean has [made updates to the rules of Hacktoberfest.](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
> 
> I am following up with our teams on this. If you don't see your count updated within a week. Do let us know.

Copy)

**Comment by Saif-Shines** [comment]
The tag is now added to the repository!

**Comment by RShalman** [comment]
> The tag is now added to the repository!

Yep, that seemed to be working now, thanks!)

**Pull request merged**
