### PR TITLE
Removing jquery on html files

### PR DESCRIPTION
**Pull request by carlospatinos**
Fix https://github.com/freshworks/marketplace-sample-apps/issues/234

### CODE REVIEW

**Comment by ravirajsubramanian** [comment]
Hi @carlospatinos,

Hi @carlospatinos,

Thanks for taking this app. Looks like some of these apps use jQuery in the scripts as well.

If they are using jQuery, please try to replace it's usage with VanillaJS scripts. (You can use [this jQuery to JS cheatsheet](https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/#document-ready) if it's helpful) or just leave those apps out of your PR.
I will create separate issues for those apps.

**Review by Saif-Shines — APPROVED** [review]
@carlospatinos 

Do you need any further help? Feel free to let us know. Once, changes are requested by @ravirajsubramanian are incorporated, we will have this PR merged. 🥇

**Comment by carlospatinos** [comment]
Looking into that, was busy

**Comment by carlospatinos** [comment]
Apologies, i think this is going take more time that i was planning to, need to look into every file making sure there is no reference there or in some js files included per page, so prefer to let someone else take it.

**Comment by ravirajsubramanian** [comment]
@carlospatinos That's fine. I will create separate PRs for the apps that use jQuery in the scripts and that are used just for the DOM load event.

Feel free to look into the other issues to contribute. 🙂

**Pull request closed without merging**
