### PR TITLE
valid link added (#306)

### PR DESCRIPTION
**Pull request by yashsehgal**
The link has been updated to (https://developers.freshworks.com/tutorials/) in the README.md file 
`Play-Around/Exercises/Readme.md`

Solving issue #306 

Please review the code changes.

### CODE REVIEW

**Review by kaustavdm — CHANGES_REQUESTED** [review]
@yashsehgal Thanks for the PR! 

Can you make a minor change? Instead of using the entire URL in the link text, have the link text say "Visit the tutorials". That will look more aesthetic IMO.

**Comment by yashsehgal** [comment]
> @yashsehgal Thanks for the PR!
> 
> Can you make a minor change? Instead of using the entire URL in the link text, have the link text say "Visit the tutorials". That will look more aesthetic IMO.

Sure @kaustavdm, I can do this 👍🏽

**Comment by yashsehgal** [comment]
I have done the changes, you may have a look 😃

**Review by kaustavdm — CHANGES_REQUESTED** [review]
Woah @yashsehgal, that was quick! 👏🏽 

My apologies, I meant to have the whole line begin with:

```md
 👉 [Visit the tutorials](https://developers.freshworks.com/tutorials/) for a guided...
```

Otherwise the sentence kinda looks redundant.

**Review by kaustavdm — APPROVED** [review]
LGTM. Thanks, @yashsehgal 🎉

**Comment by yashsehgal** [comment]
> Woah @yashsehgal, that was quick! 👏🏽
> 
> My apologies, I meant to have the whole line begin with:
> 
> ```lisp
>  👉 [Visit the tutorials](https://developers.freshworks.com/tutorials/) for a guided...
> ```
> 
> Otherwise the sentence kinda looks redundant.

Thanks, I think it's fine now 😄

**Pull request merged**
